### ISSUE TITLE
Opt out saving pseudonym profiles

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [Anthony-Reboul/AndroidDeepL#40]
At least in the German translation of https://www.deepl.com/privacy.html it is possible to opt out saving data for pseudonym user profiles (8. [...] Ich lehne die Speicherung meines Nutzerprofils ab. [...]). It works by saving a special cookie saying deepl to not save the tranfered texts. Would it be possible to implement an opt-out option for this app?

**Comment by Anthony-Reboul** [comment]
This options ask to DeepL to not generate your user profile by saving a cookie into your web browser. Since the app only use https requests, and doesn't send or save any cookie, this options it enabled by defaut ;)

**Comment by java-py-c-cpp-js** [comment]
That's good :-)
Thank you for the quick info.
