### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by protoloo** [Anthony-Reboul/AndroidDeepL#43]
Hi. If this is possible, I would like to ask to add the possibility of offline translating (after downloading the packages), especially for all those occasions when data is not working or there is no free Wi-Fi.

**Comment by Anthony-Reboul** [comment]
I would love to implement this feature, but unfortunately we only access deep learning translations via APIs, so it won't be possible to implement offline translation. There is no "translation package" to download.
