### ISSUE TITLE
App fails to open in LineageOS 14.1

### ISSUE THREAD

**Issue by amo13** [Anthony-Reboul/AndroidDeepL#46]
Thank you a lot for this great app and thank you even more for making it available on fdroid!
Unfortunately it fails to launch on my system: 
Moto G3
LineageOS 14.1 with microG (instead of GApps)
Took a logcat to help figure out the issue.
Trying to append it... Github mobile seems to still lack some important features...

**Comment by amo13** [comment]
`
09-07 20:33:10.776 E/AndroidRuntime(24147): Process: com.anthony.deepl.openl, PID: 24147
09-07 20:33:10.776 E/AndroidRuntime(24147): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-07 20:33:10.776 E/AndroidRuntime(24147): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-07 20:33:10.776 E/AndroidRuntime(24147): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-07 20:33:16.496 E/AndroidRuntime(24226): Process: com.anthony.deepl.openl, PID: 24226
09-07 20:33:16.496 E/AndroidRuntime(24226): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-07 20:33:16.496 E/AndroidRuntime(24226): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-07 20:33:16.496 E/AndroidRuntime(24226): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-07 20:33:21.252 E/AndroidRuntime(24266): Process: com.anthony.deepl.openl, PID: 24266
09-07 20:33:21.252 E/AndroidRuntime(24266): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-07 20:33:21.252 E/AndroidRuntime(24266): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-07 20:33:21.252 E/AndroidRuntime(24266): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-07 20:39:24.009 E/AndroidRuntime(24756): Process: com.anthony.deepl.openl, PID: 24756
09-07 20:39:24.009 E/AndroidRuntime(24756): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-07 20:39:24.009 E/AndroidRuntime(24756): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-07 20:39:24.009 E/AndroidRuntime(24756): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-07 20:39:26.229 E/AndroidRuntime(24780): Process: com.anthony.deepl.openl, PID: 24780
09-07 20:39:26.229 E/AndroidRuntime(24780): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-07 20:39:26.229 E/AndroidRuntime(24780): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-07 20:39:26.229 E/AndroidRuntime(24780): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-08 13:21:44.634 I/ActivityManager( 1260): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.anthony.deepl.openl/.view.translation.TranslationActivity bnds=[8,534][184,774] (has extras)} from uid 10031 on display 0
09-08 13:21:44.806 I/ActivityManager( 1260): Start proc 6513:com.anthony.deepl.openl/u0a107 for activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:21:44.919 W/System  ( 6513): ClassLoader referenced unknown path: /data/app/com.anthony.deepl.openl-1/lib/arm
09-08 13:21:45.046 I/KOIN    ( 6513): [module] declare Factory [class='com.anthony.deepl.openl.view.translation.b', binds~(androidx.lifecycle.s)]
09-08 13:21:45.049 I/KOIN    ( 6513): [module] declare Single [class='com.anthony.deepl.openl.a.a']
09-08 13:21:45.136 I/AppCompatDelegate( 6513): 	at com.anthony.deepl.openl.view.translation.TranslationActivity.onCreate(TranslationActivity.kt:44)
09-08 13:21:45.136 I/AppCompatDelegate( 6513): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.material.theme.MaterialComponentsViewInflater" on path: DexPathList[[zip file "/data/app/com.anthony.deepl.openl-1/base.apk"],nativeLibraryDirectories=[/data/app/com.anthony.deepl.openl-1/lib/arm, /system/lib, /vendor/lib]]
09-08 13:21:45.373 I/KOIN    ( 6513): +-- 'com.anthony.deepl.openl.view.translation.b' 
09-08 13:21:45.373 D/KOIN    ( 6513): |-- [Factory [class='com.anthony.deepl.openl.view.translation.b', binds~(androidx.lifecycle.s)]]
09-08 13:21:45.374 I/KOIN    ( 6513): |	+-- 'com.anthony.deepl.openl.a.a' 
09-08 13:21:45.374 D/KOIN    ( 6513): |	|-- [Single [class='com.anthony.deepl.openl.a.a']]
09-08 13:21:45.387 D/KOIN    ( 6513): |-- com.anthony.deepl.openl.view.translation.b@d9dab78
09-08 13:21:45.387 D/KOIN    ( 6513): [ViewModel] instance ~ com.anthony.deepl.openl.view.translation.b@d9dab78
09-08 13:21:45.413 E/AndroidRuntime( 6513): Process: com.anthony.deepl.openl, PID: 6513
09-08 13:21:45.413 E/AndroidRuntime( 6513): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-08 13:21:45.413 E/AndroidRuntime( 6513): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-08 13:21:45.413 E/AndroidRuntime( 6513): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-08 13:21:45.422 W/ActivityManager( 1260):   Force finishing activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:21:45.931 W/ActivityManager( 1260): Activity pause timeout for ActivityRecord{365bdf4 u0 com.anthony.deepl.openl/.view.translation.TranslationActivity t571 f}
09-08 13:21:45.944 I/WindowManager( 1260): Failed to capture screenshot of Token{ea691d ActivityRecord{365bdf4 u0 com.anthony.deepl.openl/.view.translation.TranslationActivity t571 f}} appWin=Window{b5fe078 u0 Starting com.anthony.deepl.openl} drawState=4
09-08 13:21:47.489 W/ActivityManager( 1260):   Force finishing activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:21:47.498 I/ActivityManager( 1260): Killing 6513:com.anthony.deepl.openl/u0a107 (adj 900): crash
09-08 13:25:23.047 I/ActivityManager( 1260): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:com.anthony.deepl.openl flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails} from uid 1000 on display 0
09-08 13:26:43.998 I/ActivityManager( 1260): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.anthony.deepl.openl/.view.translation.TranslationActivity bnds=[8,534][184,774] (has extras)} from uid 10031 on display 0
09-08 13:26:44.078 I/ActivityManager( 1260): Start proc 7282:com.anthony.deepl.openl/u0a107 for activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:26:44.231 W/System  ( 7282): ClassLoader referenced unknown path: /data/app/com.anthony.deepl.openl-1/lib/arm
09-08 13:26:44.360 I/KOIN    ( 7282): [module] declare Factory [class='com.anthony.deepl.openl.view.translation.b', binds~(androidx.lifecycle.s)]
09-08 13:26:44.362 I/KOIN    ( 7282): [module] declare Single [class='com.anthony.deepl.openl.a.a']
09-08 13:26:44.430 I/AppCompatDelegate( 7282): 	at com.anthony.deepl.openl.view.translation.TranslationActivity.onCreate(TranslationActivity.kt:44)
09-08 13:26:44.430 I/AppCompatDelegate( 7282): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.material.theme.MaterialComponentsViewInflater" on path: DexPathList[[zip file "/data/app/com.anthony.deepl.openl-1/base.apk"],nativeLibraryDirectories=[/data/app/com.anthony.deepl.openl-1/lib/arm, /system/lib, /vendor/lib]]
09-08 13:26:44.639 I/KOIN    ( 7282): +-- 'com.anthony.deepl.openl.view.translation.b' 
09-08 13:26:44.640 D/KOIN    ( 7282): |-- [Factory [class='com.anthony.deepl.openl.view.translation.b', binds~(androidx.lifecycle.s)]]
09-08 13:26:44.643 I/KOIN    ( 7282): |	+-- 'com.anthony.deepl.openl.a.a' 
09-08 13:26:44.643 D/KOIN    ( 7282): |	|-- [Single [class='com.anthony.deepl.openl.a.a']]
09-08 13:26:44.701 D/KOIN    ( 7282): |-- com.anthony.deepl.openl.view.translation.b@d9dab78
09-08 13:26:44.701 D/KOIN    ( 7282): [ViewModel] instance ~ com.anthony.deepl.openl.view.translation.b@d9dab78
09-08 13:26:44.725 E/AndroidRuntime( 7282): Process: com.anthony.deepl.openl, PID: 7282
09-08 13:26:44.725 E/AndroidRuntime( 7282): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-08 13:26:44.725 E/AndroidRuntime( 7282): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-08 13:26:44.725 E/AndroidRuntime( 7282): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-08 13:26:44.735 W/ActivityManager( 1260):   Force finishing activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:26:45.243 W/ActivityManager( 1260): Activity pause timeout for ActivityRecord{75e2682 u0 com.anthony.deepl.openl/.view.translation.TranslationActivity t576 f}
09-08 13:26:45.255 I/WindowManager( 1260): Failed to capture screenshot of Token{d5e3193 ActivityRecord{75e2682 u0 com.anthony.deepl.openl/.view.translation.TranslationActivity t576 f}} appWin=Window{5d083a6 u0 Starting com.anthony.deepl.openl} drawState=4
09-08 13:26:45.593 I/ActivityManager( 1260): Killing 7282:com.anthony.deepl.openl/u0a107 (adj 904): crash
09-08 13:26:45.611 I/ActivityManager( 1260): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.anthony.deepl.openl/.view.translation.TranslationActivity (has extras)} from uid 10031 on display 0
09-08 13:26:45.653 I/ActivityManager( 1260): Start proc 7320:com.anthony.deepl.openl/u0a107 for activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:26:45.728 W/System  ( 7320): ClassLoader referenced unknown path: /data/app/com.anthony.deepl.openl-1/lib/arm
09-08 13:26:45.758 I/KOIN    ( 7320): [module] declare Factory [class='com.anthony.deepl.openl.view.translation.b', binds~(androidx.lifecycle.s)]
09-08 13:26:45.758 I/KOIN    ( 7320): [module] declare Single [class='com.anthony.deepl.openl.a.a']
09-08 13:26:45.785 I/AppCompatDelegate( 7320): 	at com.anthony.deepl.openl.view.translation.TranslationActivity.onCreate(TranslationActivity.kt:44)
09-08 13:26:45.785 I/AppCompatDelegate( 7320): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.material.theme.MaterialComponentsViewInflater" on path: DexPathList[[zip file "/data/app/com.anthony.deepl.openl-1/base.apk"],nativeLibraryDirectories=[/data/app/com.anthony.deepl.openl-1/lib/arm, /system/lib, /vendor/lib]]
09-08 13:26:45.925 I/KOIN    ( 7320): +-- 'com.anthony.deepl.openl.view.translation.b' 
09-08 13:26:45.925 D/KOIN    ( 7320): |-- [Factory [class='com.anthony.deepl.openl.view.translation.b', binds~(androidx.lifecycle.s)]]
09-08 13:26:45.926 I/KOIN    ( 7320): |	+-- 'com.anthony.deepl.openl.a.a' 
09-08 13:26:45.926 D/KOIN    ( 7320): |	|-- [Single [class='com.anthony.deepl.openl.a.a']]
09-08 13:26:45.934 D/KOIN    ( 7320): |-- com.anthony.deepl.openl.view.translation.b@d9dab78
09-08 13:26:45.935 D/KOIN    ( 7320): [ViewModel] instance ~ com.anthony.deepl.openl.view.translation.b@d9dab78
09-08 13:26:45.942 E/AndroidRuntime( 7320): Process: com.anthony.deepl.openl, PID: 7320
09-08 13:26:45.942 E/AndroidRuntime( 7320): java.lang.RuntimeException: Unable to resume activity {com.anthony.deepl.openl/com.anthony.deepl.openl.view.translation.TranslationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-08 13:26:45.942 E/AndroidRuntime( 7320): 	at com.anthony.deepl.openl.e.a.a(DeeplKotlinExtentions.kt:27)
09-08 13:26:45.942 E/AndroidRuntime( 7320): 	at com.anthony.deepl.openl.view.translation.TranslationFragment.o(TranslationFragment.kt:108)
09-08 13:26:45.944 W/ActivityManager( 1260):   Force finishing activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:26:46.452 W/ActivityManager( 1260): Activity pause timeout for ActivityRecord{3e6ef8d u0 com.anthony.deepl.openl/.view.translation.TranslationActivity t577 f}
09-08 13:26:46.461 I/WindowManager( 1260): Failed to capture screenshot of Token{a5f2542 ActivityRecord{3e6ef8d u0 com.anthony.deepl.openl/.view.translation.TranslationActivity t577 f}} appWin=Window{eaba3a8 u0 Starting com.anthony.deepl.openl} drawState=4
09-08 13:26:47.237 W/ActivityManager( 1260):   Force finishing activity com.anthony.deepl.openl/.view.translation.TranslationActivity
09-08 13:26:47.242 I/ActivityManager( 1260): Killing 7320:com.anthony.deepl.openl/u0a107 (adj 902): crash
`

**Comment by Anthony-Reboul** [comment]
Thanks for the feedback and the stacktrace !
It shouldn't be to hard to fix
