### ISSUE TITLE
Network error - again: does not work anymore (Dec 15th, 2018)

### ISSUE THREAD

**Issue by rak-rak** [Anthony-Reboul/AndroidDeepL#50]
I' m aware of issue #48 (OpenL sends requests too eagerly to the deepl servers):
https://github.com/Anthony-Reboul/AndroidDeepL/issues/48

But now it does not work even when sharing a text.

**Comment by eojjn** [comment]
Is it maybe just because your IP address is blocked? I just failed to translate something via share to app so tried copying and pasting into Web version and got the message about my IP address being blocked. Worked as soon as I switched to a different IP address.

**Comment by rak-rak** [comment]
No, IP was not blocked and is still not blocked. Web interface works fine. 

IP will only be blocked, if you type directly into the app (see issue #48). 

This issue #50 is different, reproducable always network error

**Comment by rak-rak** [comment]
Thank you.
